-- ==========================================================
-- HARDWARE - Official Spare Parts & Appliance Store
-- PostgreSQL / Netlify Database Production Schema & Seed Data
-- ==========================================================

-- Enable pgcrypto extension for secure UUID / password hashing if needed
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- --------------------------------------------------------
-- Table structure for: admins
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS admins (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL DEFAULT 'Admin Staff',
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'superadmin',
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT NULL
);

-- --------------------------------------------------------
-- Table structure for: categories
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    description TEXT DEFAULT NULL,
    icon VARCHAR(50) DEFAULT 'inventory_2',
    image VARCHAR(255) DEFAULT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT NULL
);

-- --------------------------------------------------------
-- Table structure for: products
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER NOT NULL REFERENCES categories (id) ON DELETE CASCADE ON UPDATE CASCADE,
    brand VARCHAR(100) NOT NULL DEFAULT 'Universal',
    product_name VARCHAR(200) NOT NULL,
    sku VARCHAR(80) NOT NULL UNIQUE,
    size VARCHAR(80) DEFAULT 'Standard',
    description TEXT DEFAULT NULL,
    specs JSONB DEFAULT NULL,
    price NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    original_price NUMERIC(10,2) DEFAULT NULL,
    stock_quantity INTEGER NOT NULL DEFAULT 0,
    image VARCHAR(255) DEFAULT 'default.svg',
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_status ON products(status);
CREATE INDEX IF NOT EXISTS idx_products_is_featured ON products(is_featured);

-- --------------------------------------------------------
-- Table structure for: inquiries
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS inquiries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER DEFAULT NULL REFERENCES products (id) ON DELETE SET NULL ON UPDATE CASCADE,
    customer_name VARCHAR(100) NOT NULL,
    customer_phone VARCHAR(30) NOT NULL,
    customer_email VARCHAR(150) DEFAULT NULL,
    message TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'in_progress', 'completed', 'cancelled')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_inquiry_product ON inquiries(product_id);
CREATE INDEX IF NOT EXISTS idx_inquiry_status ON inquiries(status);

-- ==========================================================
-- SEED DATA (Preserving Exact Business Records)
-- ==========================================================

-- Seed Admins (1 Administrator)
INSERT INTO admins (id, name, email, password, role, status, created_at)
VALUES (
    1,
    'Sameer Admin',
    'Sameer3111@AA.com',
    '$2y$10$dWkCzJyxzTMkutRscWJnLeDr4FDtu51OLcjylmSvAxnt4BMG.psVa',
    'superadmin',
    'active',
    CURRENT_TIMESTAMP
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    email = EXCLUDED.email,
    password = EXCLUDED.password,
    role = EXCLUDED.role,
    status = EXCLUDED.status;

-- Seed Categories (5 Categories)
INSERT INTO categories (id, name, slug, description, icon, status, created_at)
VALUES
(1, 'AC', 'ac', 'Air Conditioner parts, compressors, filters, remotes and PCB boards', 'mode_fan', 'active', CURRENT_TIMESTAMP),
(2, 'Washing machine', 'washing-machine', 'Washers, drain pumps, inlet valves, timers, drums and pulsators', 'local_laundry_service', 'active', CURRENT_TIMESTAMP),
(3, 'Refrigerator', 'refrigerator', 'Fridges, defrost thermostats, relays, gas charging valves, door gaskets', 'kitchen', 'active', CURRENT_TIMESTAMP),
(4, 'Micro oven', 'micro-oven', 'Microwave ovens, high voltage magnetrons, capacitors, glass plates, diodes', 'microwave', 'active', CURRENT_TIMESTAMP),
(5, 'Water purifier', 'water-purifier', 'RO membranes, sediment filters, carbon blocks, booster pumps, adapters', 'water_drop', 'active', CURRENT_TIMESTAMP)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    description = EXCLUDED.description,
    icon = EXCLUDED.icon,
    status = EXCLUDED.status;

-- Seed Products (8 Genuine OEM Spare Parts)
INSERT INTO products
(id, category_id, brand, product_name, sku, size, description, specs, price, original_price, stock_quantity, image, is_featured, status, created_at)
VALUES
(
    1, 1,
    'LG, Samsung, Daikin, Voltas',
    'AC Air Filter',
    'AC-FILT-STD-01',
    'Standard',
    'High density washable poly-mesh air filter suitable for all split and window air conditioner models.',
    '{"material":"HD Polypropylene Mesh","washable":"Yes","dimensions":"305mm x 310mm","warranty":"6 Months"}'::jsonb,
    350.00,
    499.00,
    18,
    'ac-air-filter.svg',
    TRUE,
    'active',
    CURRENT_TIMESTAMP
),
(
    2, 1,
    'LG, Daikin, Voltas, Hitachi',
    'AC Compressor',
    'AC-COMP-ROT-02',
    '1.5 Ton / 2 Ton',
    'Original heavy duty rotary inverter compressor engineered for 1.5T to 2T energy efficient cooling units.',
    '{"type":"Rotary Inverter Compressor","refrigerant":"R32 / R410A","displacement":"14.2 cc","warranty":"3 Years Store Warranty"}'::jsonb,
    7850.00,
    9500.00,
    7,
    'ac-compressor.svg',
    TRUE,
    'active',
    CURRENT_TIMESTAMP
),
(
    3, 1,
    'Universal, All Brands',
    'AC Remote Control',
    'AC-REM-UNI-03',
    'Universal',
    'Universal replacement remote controller pre-programmed with 1000+ brand codes and backlit LCD display.',
    '{"display":"Backlit LCD Display","distance":"Up to 8 Meters","compatibility":"1000+ Codes pre-programmed","battery":"2x AAA Included"}'::jsonb,
    450.00,
    650.00,
    42,
    'ac-remote-control.svg',
    TRUE,
    'active',
    CURRENT_TIMESTAMP
),
(
    4, 1,
    'LG, Samsung, Daikin, Voltas',
    'AC PCB Board',
    'AC-PCB-INV-04',
    '1.5 Ton / 2 Ton',
    'Dual inverter control mother board with surge protection and heat-resistant industrial conformal coating.',
    '{"type":"Dual Inverter Control Board","protection":"Surge & Heat Resistant Coating","voltage":"220V 50Hz","status":"Backorder available in 3 days"}'::jsonb,
    3200.00,
    3900.00,
    0,
    'ac-pcb-board.svg',
    FALSE,
    'active',
    CURRENT_TIMESTAMP
),
(
    5, 2,
    'LG, Samsung',
    'Washing Machine Drain Pump',
    'WM-PUMP-05',
    'Standard',
    'High-torque magnetic synchronous drain pump designed for automatic front-load and top-load washers.',
    '{"wattage":"30W 220V","type":"Magnetic Synchronous Pump","warranty":"1 Year"}'::jsonb,
    850.00,
    1100.00,
    15,
    'wm-drain-pump.svg',
    TRUE,
    'active',
    CURRENT_TIMESTAMP
),
(
    6, 3,
    'Whirlpool, Samsung, LG',
    'Refrigerator Defrost Thermostat',
    'RF-THERM-06',
    'Standard',
    'Bi-metal hermetically sealed defrost bi-metal thermostat with safety cut-off fuse protection.',
    '{"cutOffTemp":"+10°C","cutInTemp":"-5°C","waterproof":"Bi-metal Sealed"}'::jsonb,
    380.00,
    520.00,
    22,
    'rf-thermostat.svg',
    TRUE,
    'active',
    CURRENT_TIMESTAMP
),
(
    7, 4,
    'LG, Samsung, IFB',
    'Microwave High Voltage Magnetron',
    'MO-MAGN-07',
    'Universal',
    'Industrial-grade 900W 2450MHz microwave heating magnetron tube with dual air-cooled cooling fin array.',
    '{"frequency":"2450 MHz","output":"900W","cooling":"Air-cooled fin array"}'::jsonb,
    1450.00,
    1850.00,
    9,
    'mo-magnetron.svg',
    TRUE,
    'active',
    CURRENT_TIMESTAMP
),
(
    8, 5,
    'Kent, Aquaguard, All Brands',
    'Water Purifier RO Membrane 75 GPD',
    'WP-MEMB-08',
    'Standard',
    '0.0001 Micron thin-film composite polyamide reverse osmosis membrane with 97% mineral salt rejection.',
    '{"capacity":"75 Gallons/day (0.0001 Micron)","material":"Polyamide Thin Film","saltRejection":"97%"}'::jsonb,
    1150.00,
    1600.00,
    30,
    'wp-ro-membrane.svg',
    TRUE,
    'active',
    CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
    category_id = EXCLUDED.category_id,
    brand = EXCLUDED.brand,
    product_name = EXCLUDED.product_name,
    sku = EXCLUDED.sku,
    size = EXCLUDED.size,
    description = EXCLUDED.description,
    specs = EXCLUDED.specs,
    price = EXCLUDED.price,
    original_price = EXCLUDED.original_price,
    stock_quantity = EXCLUDED.stock_quantity,
    image = EXCLUDED.image,
    is_featured = EXCLUDED.is_featured,
    status = EXCLUDED.status;

-- Seed Inquiries (3 Realistic Technician / Wholesale Inquiries)
INSERT INTO inquiries
(id, product_id, customer_name, customer_phone, customer_email, message, status, created_at)
VALUES
(
    1, 2,
    'Rajesh Kumar (Technician)',
    '+91 98450 12345',
    'rajesh.cooltech@gmail.com',
    'Need bulk pricing for 5 units of 1.5 Ton AC Rotary Compressor for immediate site delivery.',
    'new',
    CURRENT_TIMESTAMP - INTERVAL '2 hours'
),
(
    2, 4,
    'Anand Verma',
    '+91 97412 88990',
    'anand.service@outlook.com',
    'Is the Dual Inverter AC PCB board compatible with 2022 Daikin Split model FTKP50?',
    'in_progress',
    CURRENT_TIMESTAMP - INTERVAL '1 day'
),
(
    3, 8,
    'Suresh Reddy',
    '+91 99001 44332',
    'suresh.r@yahoo.com',
    'Looking for 10x RO membrane 75 GPD with pre-filter set for wholesale order.',
    'completed',
    CURRENT_TIMESTAMP - INTERVAL '3 days'
)
ON CONFLICT (id) DO UPDATE SET
    product_id = EXCLUDED.product_id,
    customer_name = EXCLUDED.customer_name,
    customer_phone = EXCLUDED.customer_phone,
    customer_email = EXCLUDED.customer_email,
    message = EXCLUDED.message,
    status = EXCLUDED.status;

-- Synchronize Identity Sequences
SELECT setval(pg_get_serial_sequence('admins', 'id'), COALESCE((SELECT MAX(id) FROM admins), 1));
SELECT setval(pg_get_serial_sequence('categories', 'id'), COALESCE((SELECT MAX(id) FROM categories), 1));
SELECT setval(pg_get_serial_sequence('products', 'id'), COALESCE((SELECT MAX(id) FROM products), 1));
SELECT setval(pg_get_serial_sequence('inquiries', 'id'), COALESCE((SELECT MAX(id) FROM inquiries), 1));
